# Generated by Django 4.2 on 2023-05-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_label_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edt",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
