# Generated by Django 4.2 on 2023-05-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_edt_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="label",
        ),
    ]
