# Generated by Django 4.2 on 2023-05-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_room_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="sessionRooms",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="part",
            name="sessionTeachers",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
