# Generated by Django 4.2 on 2023-05-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_part_sessionrooms_alter_part_sessionteachers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Class",
            new_name="Classe",
        ),
    ]
