# Generated by Django 4.2 on 2023-05-10 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_class_name_groupclass_classe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupclass",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.classe",
            ),
        ),
    ]
