# Generated by Django 4.2 on 2023-05-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_groupclass_classe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="class_obj",
            new_name="classe",
        ),
        migrations.RenameField(
            model_name="sessionteacher",
            old_name="class_obj",
            new_name="classe",
        ),
    ]
