# Generated by Django 4.2 on 2023-05-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_class_obj_session_classe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionroom",
            old_name="class_obj",
            new_name="classe",
        ),
    ]
