# Generated by Django 4.2 on 2023-05-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edt",
            name="user",
        ),
    ]
