# Generated by Django 4.2 on 2023-05-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Edt",
        ),
    ]
