# Generated by Django 4.2 on 2023-05-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partname", models.CharField(max_length=255)),
                ("nrSessions", models.IntegerField()),
                ("maxHeadCount", models.IntegerField()),
                ("sessionLength", models.IntegerField()),
                ("dailySlots", models.CharField(max_length=255)),
                ("days", models.CharField(max_length=255)),
                ("weeks", models.CharField(max_length=255)),
                (
                    "sessionRooms",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "sessionTeachers",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "edt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.edt"
                    ),
                ),
            ],
        ),
    ]
